Update Neovim.ts
neovim/node-client pull request #186
Opened 2021-12-11 07:36 UTC by KadoBOT

Add `style` to OpenWindowOptions

2021-12-11 15:51 UTC, rhysd requested changes

2021-12-11 15:51 UTC, rhysd commented on packages/neovim/src/api/Neovim.ts
> +  style?: 'minimal'
`;` is missing at end of line

2021-12-11 15:52 UTC, rhysd commented
@KadoBOT Can you show a link to document of the `style` option in Neovim?

2021-12-12 01:43 UTC, rhysd approved these changes

2021-12-12 01:44 UTC, rhysd commented
https://dev.azure.com/neovim/node-client/_build/results?buildId=216&view=logs&j=775b36c7-0acf-56fe-5683-ee983d10b23d&t=db2cdf11-2dd7-537a-2325-1e72eed53a44&l=28

Can you resolve the prettier warning?

```
/Users/runner/work/1/s/packages/neovim/src/api/Neovim.ts
  103:1  error  Delete `··`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

2021-12-12 08:40 UTC, rhysd commented
Yeah, I believe they are valid.

2021-12-12 08:40 UTC, merged

2021-12-12 08:42 UTC, rhysd commented
@billyvg @justinmk Can we make a new release?

2021-12-13 15:17 UTC, billyvg commented
4.10.1 published -- thoughts on moving to GitHub Actions? Can move add a publish workflow when we make a GitHub Release too.

2021-12-13 15:35 UTC, rhysd commented
> thoughts on moving to GitHub Actions? 

That would be nice idea though I'm not understanding how to manage npm credentials and 2FA on GHA.